restaurant_project/procesos/urls.py
from django.conf.urls import url
from procesos import views
from django.contrib.auth.decorators import login_required

app_name = 'procesos'

urlpatterns = [
    url(r'^usuarios/', login_required(views.registro_usuario), name='registro_usuarios'),
    url(r'^sesion_caja/', login_required(views.sesion_caja), name='sesion_caja'),
    url(r'^create_sesion_caja/', login_required(views.CreateSesionCaja.as_view()), name='create_sesion_caja'),
    url(r'^cerrar_sesion_caja/', login_required(views.CerrarSesionCaja.as_view()), name='cerrar_sesion_caja'),
    url(r'^lista_sesion_caja/', login_required(views.SesionList.as_view()), name='lista_sesion_caja'),
    url(r'^detalle_sesion_caja/', login_required(views.DetalleSesionCaja.as_view()), name='detalle_sesion_caja'),
    # urls utiles para realizar ordenes
    url(r'^panel_mesas/', login_required(views.PanelMesasView.as_view()), name='panel_mesas'),
    url(r'^abrir_orden/', login_required(views.AbrirOrden.as_view()), name='abrir_orden'),
    url(r'^detalle_orden/(?P<pk>\d+)/$', login_required(views.detalle_orden.as_view()), name='detalle_orden'),
    url(r'^orden_detail/', login_required(views.OrdenDetail.as_view()), name='orden_detail'),
    url(r'^orden_condetalles_detail/', login_required(views.OrdenConDetallesDetailList.as_view()), name='orden_condetalle_detail'),
    url(r'^lista_ordenes/', login_required(views.GetOrdenesList.as_view()), name='orden_list'),
    url(r'^lista_ordenesporestado', login_required(views.GetOrdenesPorEstadoList.as_view()), name='orden_porestado_list'),
    url(r'^ordenes_activas', login_required(views.OrdenesActivas.as_view()), name='ordenes_activas'),
    url(r'^orden_update', login_required(views.GetOrdenesUpdate.as_view()), name='orden_update'),
    url(r'^orden_id', login_required(views.OrdenPago.as_view()), name="orden_id"),
    url(r'^lista_perfiles', login_required(views.PerfilDeUsuarioList.as_view()), name="lista_perfiles"),
    # urls utiles para realizar detalle de orden
    url(r'^create_detalle_orden', login_required(views.CreateDetalleOrden.as_view()), name='create_detalle_orden'),
    url(r'^update_detalle_orden', login_required(views.UpdateDetalleOrden.as_view()), name='update_detalle_orden'),
    url(r'^delete_detalle_orden', login_required(views.DeleteDetalleOrden.as_view()), name='delete_detalle_orden'),
    url(r'^detail_detalle_orden', login_required(views.DetalleOrdenDetail.as_view()), name='detail_detalle_orden'),
    # facturar
    url(r'^facturar', login_required(views.FacturarView.as_view()), name='facturar'),
    url(r'^detail_orden_mesa', login_required(views.OrdenDetailMesa.as_view()), name='detail_orden_mesa'),
    url(r'^pago/(?P<pk>\d+)/$', login_required(views.PagoView.as_view()), name="pago"),
    url(r'^pago/(?P<pk>\d+)/pdf/$', login_required(views.FacturaView.as_view()), name="factura_pdf"),
    url(r'^create_pago', login_required(views.GetCreatePago.as_view()), name="create_pago"),
    # historial de ordenes
    url(r'^historial', login_required(views.HistorialList.as_view()), name='historial'),
]

restaurant_project/restaurant_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from procesos import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^restaurant/', include('restaurant_application.urls')),
    url(r'^inventario/', include('inventario.urls')),
    url(r'^procesos/', include('procesos.urls')),
    url(r'^logout/', views.user_logout, name='logout'),
    url(r'^login', views.user_login, name='login'),
    url(r'^$', views.index, name='index'),
]

restaurant_project/procesos/forms.py
from django import forms
from django.contrib.auth.models import User
from procesos.models import PerfilDeUsuario, Sesion, Orden
from restaurant_application.models import Asignacion, Empleado, Puesto

class UsuarioForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'password')

class PerfilDeUsuarioForm(forms.ModelForm):
    class Meta():
        model = PerfilDeUsuario
        fields = ('empleado', 'foto_de_perfil')

class SesionForm(forms.ModelForm):

    class Meta():
        model = Sesion
        fields = ('caja', 'cajero', 'fecha_cierre', 'monto_apertura', 'monto_real', 'estado')
        widgets = {
            'caja':forms.Select(attrs={'class':'form-control','id':'selectCaja'}),
            'cajero':forms.Select(attrs={'class':'form-control','id':'selectCajero'}),
            'monto_apertura':forms.TextInput(attrs={'class':'form-control','id':'txtMontoApertura'}),
            'monto_real':forms.TextInput(attrs={'class':'form-control','id':'txtMontoReal'}),
        }

class OrdenForm(forms.ModelForm):
    class Meta():
        model = Orden
        fields = ('mesero', 'comentario')
        widgets = {
            'mesero':forms.Select(attrs={'class':'form-control','id':'selectMesero'}),
            'comentario':forms.Textarea({'class':'form-control','rows':'5','id':'txtComentario'})
        }

restaurant_project/procesos/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response
from procesos.forms import PerfilDeUsuarioForm, UsuarioForm, SesionForm, OrdenForm
from procesos.serializers import SesionSerializer, OrdenSerializer, DetalleOrdenSerializer, Orden_ConDetalle_Serializer, PerfilDeUsuarioSerializer
from procesos.models import Sesion, Orden, DetalleOrden, cantidad_ordenes_del_dia, Pago, PerfilDeUsuario
from restaurant_application.models import Asignacion, Empleado, Puesto, Caja, Cliente, Mesa, Platillo
from django.http import JsonResponse
import datetime
from django.views.generic import ListView, CreateView, DetailView
from django.views import View
from io import BytesIO
from reportlab.pdfgen import canvas
from reportlab.lib.units import cm
from reportlab.lib.pagesizes import letter
# use estos para el login

from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
# Vistas
def registro_usuario(request):
    registered = False

    if request.method == 'POST':
        user_form = UsuarioForm(data=request.POST)
        profile_form = PerfilDeUsuarioForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.usuario = user

            if 'foto_de_perfil' in request.FILES:
                profile.foto_de_perfil = request.FILES['foto_de_perfil']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UsuarioForm()
        profile_form = PerfilDeUsuarioForm()

    context_dict = {
        "registered": registered,
        "user_form": user_form,
        "profile_form": profile_form
    }

    return render(request, 'procesos/registro_usuario.html', context=context_dict)

def sesion_caja(request):
    form = SesionForm()
    context = {'form':form}
    return render(request, 'procesos/sesion_caja/index.html', context)

class CreateSesionCaja(APIView):
    def get(self, request):
        caja = Caja.objects.filter(id=request.GET['numero_caja']).get()
        cajero = Empleado.objects.filter(idEmpleado=request.GET['idEmpleado']).get()
        tiene_sesion = False
        # verificando si ese cajero ya tiene sesion
        sesiones = Sesion.objects.all()
        for sesion in sesiones:
            if sesion.cajero.idEmpleado == cajero.idEmpleado and sesion.estado == "Abierta":
                tiene_sesion = True
            # end if
        #end for
        try:
            if not tiene_sesion:
                sesion = Sesion.objects.create(caja = caja, cajero=cajero, monto_apertura=request.GET['monto_apertura'], estado="Abierta")
            else:
                raise NameError("El cajero ya tiene una sesión activa")
            #end if
        except NameError:
            raise
        return JsonResponse({'respuesta':'correctamente!'})

class CerrarSesionCaja(APIView):
    def get(self, request):
        fecha_cierre = datetime.datetime.now()
        #fecha_cierr = fecha_cierre.year+"-"fecha_cierre.month+"-"+fecha_cierre.day+" "+fecha_cierre.hour+":"fecha_cierre.minute+":"fecha_cierre.second
        sesion = Sesion.objects.filter(id=request.GET['id']).update(monto_real=request.GET['monto_real'], fecha_cierre=fecha_cierre, estado="Cerrada")
        return JsonResponse({'respuesta':'correctamente!'})

class SesionList(APIView):
    def get(self, request):
        sesiones = Sesion.objects.all().order_by("-id")
        serialized = SesionSerializer(sesiones, many=True)
        return Response(serialized.data)

class DetalleSesionCaja(APIView):
    def get(self, request):
        sesiones = Sesion.objects.filter(id=request.GET['id'])
        serialized = SesionSerializer(sesiones, many=True)
        return Response(serialized.data)

class PanelMesasView(ListView):
    def get(self, request):
        formOrdenar = OrdenForm()
        context = {'formOrdenar':formOrdenar}
        return render(request, 'procesos/mesas.html', context)

class AbrirOrden(APIView):
    def get(self, request):
        user_id = request.user.id
        perfil = PerfilDeUsuario.objects.filter(usuario=user_id).get()
        sesion = Sesion.objects.filter(cajero=perfil.empleado.idEmpleado, estado="Abierta")
        empleado = Empleado.objects.filter(idEmpleado=request.GET['idEmpleado'])
        mesa = Mesa.objects.filter(codigo_mesa=request.GET['codigo_mesa'])
        mesa.update(ocupado=True)
        orden = Orden.objects.create(sesion=sesion[0],numero_orden=cantidad_ordenes_del_dia() + 1, mesero=empleado[0], cliente=request.GET['cliente'], mesa=mesa[0], comentario=request.GET['comentario'])
        return JsonResponse({'respuesta':orden.id})

class detalle_orden(DetailView):
    model = Orden
    template_name = 'procesos/detalle_orden.html'

class OrdenDetail(APIView):
    def get(self, request):
        orden = Orden.objects.filter(id=request.GET['id'])
        serialized = OrdenSerializer(orden, many=True)
        return Response(serialized.data)

class OrdenDetailMesa(APIView):
    def get(self, request):
        mesa = Mesa.objects.filter(codigo_mesa=request.GET['codigo_mesa'])
        orden = Orden.objects.filter(mesa=mesa[0], estado="No Finalizado")
        serialized = OrdenSerializer(orden, many=True)
        return Response(serialized.data)

class OrdenConDetallesDetailList(APIView):
    def get(self, request):
        ordenes = Orden.objects.filter(estado=request.GET['estado'])
        serialized = Orden_ConDetalle_Serializer(ordenes, many=True)
        return Response(serialized.data)

class PerfilDeUsuarioList(APIView):
    def get(self, request):
        perfiles = PerfilDeUsuario.objects.all()
        serialized = PerfilDeUsuarioSerializer(perfiles, many=True)
        return Response(serialized.data)

class OrdenPago(APIView):
    def get(self, request):
        orden = Orden.objects.filter(id=request.GET['id']).get()

        return Response(serialized.data)

class GetOrdenesList(APIView):
    def get(self, request):
        ordenes = Orden.objects.all()
        serialized = OrdenSerializer(ordenes, many=True)
        return Response(serialized.data)

class GetOrdenesPorEstadoList(APIView):
    def get(self, request):
        ordenes = Orden.objects.filter(estado=request.GET["estado"])
        serialized = OrdenSerializer(ordenes, many=True)
        return Response(serialized.data)

class GetOrdenesUpdate(APIView):
    def get(self, request):
        id = request.GET["id"]
        estado = request.GET["estado"]
        orden = Orden.objects.filter(id=id)
        orden.update(estado=estado)
        mesa = Mesa.objects.filter(codigo_mesa=orden[0].mesa.codigo_mesa)
        mesa.update(ocupado=False)

        return Response({"respuesto": "ok"})

class HistorialList(ListView):
    queryset = Orden.objects.filter(estado='finalizada')
    template_name = 'procesos/historial.html'

class detalle_orden(DetailView):
    model = Orden
    template_name = 'procesos/detalle_orden.html'
class FacturarView(View):
    def get(self, request):
        return render(request, 'procesos/facturar.html')

class OrdenesActivas(View):
    def get(self, request):
        return render(request, 'procesos/ordenes_activas.html')

class CreateDetalleOrden(APIView):
    def get(self, request):
        orden = Orden.objects.filter(id=request.GET['id'])
        consumible = Platillo.objects.filter(codigoPlatillo=request.GET['codigoPlatillo'])
        detalleorden = DetalleOrden.objects.create(orden=orden[0], consumible=consumible[0], precio_de_venta=request.GET['precio'], comentario='')
        return JsonResponse({'id':detalleorden.id})

class UpdateDetalleOrden(APIView):
    def get(self, request):
        detalleorden = DetalleOrden.objects.filter(id=request.GET['id']).update(cantidad=request.GET['cantidad'], ordenados=request.GET['ordenados'], entregados=request.GET['entregados'], precio_de_venta=request.GET['precio'], comentario='', descuento=request.GET['descuento'])
        return JsonResponse({'respuesta':' correctamente!'})

class DeleteDetalleOrden(APIView):
    def get(self, request):
        detalleorden = DetalleOrden.objects.filter(id=request.GET['id']).delete()
        return JsonResponse({'respuesta':' correctamente!'})

class DetalleOrdenDetail(APIView):
    def get(self, request):
        orden = Orden.objects.filter(id=request.GET['id'])
        detalleordenes = DetalleOrden.objects.filter(orden=orden[0])
        serialized = DetalleOrdenSerializer(detalleordenes, many=True)
        return Response(serialized.data)

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Cuenta no activada')
        else:
            print("Alguien intentó ingresar y no pudo.")
            print("Usuario: {} y contraseña: {}".format(username, password))
            return HttpResponse("Proprocionó datos de ingreso erróneos.")
    else:
        return render(request, 'login.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('login'))

@login_required
def index(request):
    return render(request, 'index.html')

class PagoView(View):
    def get(self, request, pk):
        return render(request, "procesos/pago.html", {"pk":pk})


class Pagar(APIView):
    def get(self, request):

restaurant_project/templates/procesos/abrir_orden_formulario.html
<div class="modal-body">
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <label>Nombre de Cliente</label>
        <input type="text" class="form-control" id="txtNombreCliente">
        <small class="form-text text-muted"></small>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <label>Mesero</label>
        <select name="mesero" class="form-control" id="selectMesero" required="">

        </select>
        <small class="form-text text-muted"></small>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <label>Comentario</label>
        {{ formOrdenar.comentario }}
        <small class="form-text text-muted"></small>
      </div>
    </div>
  </div>
</div>
<div class="modal-footer">
  <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
  <button id="btn-guardar" type="button" class="btn btn-primary" value="">Guardar</button>
</div>

restaurant_project/templates/procesos/facturar.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block TitlePage %}
    {{'Procesos | Facturación'}}
{% endblock %}
{% block body %}
    <div class="container">
        <!-- breadcrumbs -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="#">Procesos</a>
            </li>
            <li class="breadcrumb-item active">
                <a href="#">Facturación</a>
            </li>
        </ol>
        <h3>Ordenes pendientes de facturación</h3>
        <div id="facturar">
            <table class="table table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th>
                            Orden
                        </th>
                        <th>
                            Hora
                        </th>
                        <th>
                            Estado
                        </th>
                        <th>
                            Mesa
                        </th>
                        <th>
                            Cliente
                        </th>
                        <th>
                            Mesero
                        </th>
                        <th>
                            Total
                        </th>
                        <th>
                            Opciones
                        </th>
                    </tr>
                </thead>
                <tbody id="bfacturar">

                </tbody>
            </table>
        </div>
    </div>

    {% include 'base/modal.html' %}

{% endblock %}

{% block JavaScriptFiles %}
<script src="{% static 'js/accounting.min.js' %}"></script>
<script>
    var obtenerDatos = () => {
        $.ajax({
            url: "{% url 'procesos:orden_condetalle_detail' %}",
            data: {
                estado: "Finalizada"
            },
            dataType: "JSON",
            type: "GET",
            success: (data) => {
                console.log(data);
                let html = ``;
                for(let i = data.length - 1; i >= 0; i--)
                {
                    orden = data[i];
                    orden.fecha_orden = new Date(orden.fecha_orden);
                    html += `<tr>
                        <td>${orden.numero_orden}</td>
                        <td>${orden.fecha_orden.toLocaleTimeString()}</td>
                        <td>${orden.estado}</td>
                        <td>${orden.mesa.numero_mesa}</td>
                        <td>${orden.cliente}</td>
                        <td>${orden.mesero.nombre} ${orden.mesero.apellido}</td>
                        <td>${accounting.formatMoney(orden.total)}</td>
                        <td>
                            <a href="/procesos/pago/${orden.id}/">
                                <button class="btn btn-success">Pagar</button>
                            </a>
                        </td>
                    </tr>`;
                }
                $("#bfacturar").html(html);
            }
        });
    };
    $(document).ready(function(){
        obtenerDatos();
    });
</script>
{% endblock %}

restaurant_project/templates/procesos/ordenes_activas.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block TitlePage %}
    {{'Ordenes | Ordenes activas'}}
{% endblock %}
{% block body %}
<div class="container">
    <!-- breadcrumbs -->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="#">Procesos</a>
        </li>
        <li class="breadcrumb-item">
            <a href="#">Ordenes</a>
        </li>
        <li class="breadcrumb-item active">
            Ordenes activas
        </li>
    </ol>
    <!-- tabla pedidos -->
    <table class="table table-striped" id="tabla-ordenes-activas">
        <thead class="thead-dark">
            <tr>
                <th>Orden</th>
                <th>Hora de la orden</th>
                <th>Estado</th>
                <th>Mesa</th>
                <th>Mesero</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            
        </tbody>
    </table>
    <!-- finalizar modal -->
    <div class="modal" tabindex="-1" id="finalizar-modal" role="dialog">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title">Está seguro de que desea finalizar la orden?</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-footer">
                  <button type="button" id="finalizar-btn" class="btn btn-danger">Finalizar</button>
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                </div>
              </div>
            </div>
          </div>
</div>
{% endblock %}

{% block JavaScriptFiles %}
    <script>
        var llenarTabla = () => {
            $.ajax({
                url: "{% url 'procesos:orden_porestado_list' %}",
                data: {
                    estado: "No Finalizado"
                },
                type: 'GET',
                dataType: 'json',
                success: (data) => {
                    let tbody = $("#tabla-ordenes-activas tbody");
                    html = ``;
                    for(let i = 0; i < data.length; i++){
                        let orden = data[i];
                        orden.fecha_orden = new Date(orden.fecha_orden)
                        html += `
                        <tr>
                            <td>${orden.numero_orden}</td>
                            <td>${orden.fecha_orden.toLocaleTimeString()}</td>
                            <td>${orden.estado}</td>
                            <td>Mesa ${orden.mesa.numero_mesa}</td>
                            <td>${orden.mesero.nombre} ${orden.mesero.apellido}</td>
                            <td>
                                <a href="/procesos/detalle_orden/${orden.id}/" class="btn btn-success">
                                    Detalles
                                <a/>
                                <button class="btn btn-danger btn-finalizar" value="${orden.id}">Finalizar</button>
                            </td>
                        </tr>
                        `;
                    }
                    tbody.html(html);
                }
                
            });
        }
        $(document)
        .ready(() => {
            llenarTabla();
        });
        $(document).on("click", ".btn-finalizar", function(){
            $("#finalizar-modal").modal("show");
            $("#finalizar-btn").val($(this).val());
        });
        $(document).on("click", "#finalizar-btn", function(){
            $.ajax({
                url: "{% url 'procesos:orden_update' %}",
                data: {
                    id: $(this).val(),
                    estado: "Finalizada"
                },
                dataType: "json",
                type: "GET",
                success: (data) => {
                    $("#finalizar-modal").modal("hide");
                    llenarTabla();
                }
            });
        });
    </script>
{% endblock %}

restaurant_project/templates/procesos/pago.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block TitlePage %}
    {{'Procesos | Pago'}}
{% endblock %}
{% block body %}

    <div class="container">
        <!-- breadcrumbs -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="#">Procesos</a>
            </li>
            <li class="breadcrumb-item active">
                <a href="#">Pago</a>
            </li>
        </ol>

        <form class="form" id="form-pago">
            <table style="display: inline-block;">
                <tr>
                    <td><label for="debe">Debe</label></td>
                    <td><label for="entregado">Entregado</label></td>
                    <td><label for="cambio">Cambio</label></td>
                </tr>
                <tr>
                    <td><span id="debe"></span></td>
                    <td><input type="text" id="entregado" placeholder="Efectivo entregado"/></td>
                    <td><span id="cambio"></span></td>
                </tr>
            </table>
            <a class="btn btn-primary" id="btn-pago" href="pdf">Validar</a>
            <br><br>
        </form>
        <table class="table table-striped">
                <thead class="thead-dark">
                    <tr>
                        <th>
                            Orden
                        </th>
                        <th>
                            Hora
                        </th>
                        <th>
                            Mesa
                        </th>
                        <th>
                            Cliente
                        </th>
                        <th>
                            Mesero
                        </th>
                        <th>
                            Propina
                        </th>
                        <th>
                            Total
                        </th>
                    </tr>
                </thead>
                <tbody id="bpagar">

                </tbody>
            </table>
    </div>


{% endblock %}

{% block JavaScriptFiles %}
<script src="{% static 'js/accounting.min.js' %}"></script>
<script>
    $(document).ready(function(){
        $.ajax({
            url: "{% url 'procesos:orden_id' %}",
            data: {
                id:"{{ pk }}"
            },
            dataType: "JSON",
            type: "GET",
            success: (data) => {
                data.fecha_orden = new Date(data.fecha_orden);
                html = `<tr>
                    <td>${data.numero_orden}</td>
                    <td>${data.fecha_orden.toLocaleTimeString()}</td>
                    <td>${data.mesa.numero_mesa}</td>
                    <td>${data.cliente}</td>
                    <td>${data.mesero.nombre} ${data.mesero.apellido}</td>
                    <td>${data.propina*100}%</td>
                    <td>${accounting.formatMoney(data.total)}</td>
                </tr>`;
                $("#bpagar").html(html);
                $("#debe").text(accounting.formatMoney(data.total));
                $("#cambio").text(accounting.formatMoney(0));
            }

        });
    });

    $('#entregado').on('input propertychange paste', function() {
        if($.isNumeric($("#entregado").val()))
        {
            $("#cambio").text(accounting.formatMoney(parseFloat(accounting.unformat($("#debe").text())) - $("#entregado").val()));
        }
        if($("#entregado").val() == "")
        {
            $("#cambio").text(accounting.formatMoney(0));
        }
    });

    $(document).on("click", "#btn-pago", function(){
        if($.isNumeric($("#entregado").val()))
        {
            if($("#entregado").val() > parseFloat(accounting.unformat($("#debe").text()))){
                // generar pdf de la factura
                let downloadPromise = new Promise((resolve, reject) => {
                    $.ajax({
                        url: '{% url 'procesos:factura_pdf' pk=pk %}',
                        method: 'GET',
                        xhrFields: {
                            responseType: 'blob'
                        },
                        success: function(data)
                        {
                            let a = document.createElement('a');
                            let url = window.URL.createObjectURL(data);
                            a.href = url;
                            a.download = 'factura.pdf';
                            a.click();
                            window.URL.revokeObjectURL(url);
                            $.ajax({
                                url: '{% url 'procesos:orden_update' %}',
                                type: 'GET',
                                data: {
                                    id: "{{ pk }}",
                                    estado: "Facturada"
                                },
                                dataType: 'JSON',
                                success: function(data){
                                    $.ajax({
                                        url: "{% url 'procesos:create_pago' %}",
                                        type: 'GET',
                                        data: {
                                            id: "{{ pk }}",
                                            entregado: $("#entregado").val()
                                        },
                                        dataType: "JSON",
                                        success: function(data){
                                            resolve("{% url 'procesos:facturar' %}");
                                        }
                                    });
                                }
                            });
                        }
                    });
                }); //fin del promise
                downloadPromise.then(function(val){
                    window.location.href = val;
                    return false;
                })
                .catch(function(err){
                    alert(err);
                });
            }
            else
            {
                alert("El efectivo entregado debe ser mayor a lo que debe el cliente.");
            }
        }
        else{
            alert("Ingrese un valor numerico");
        }
        return false;
    });
</script>
<style>
    td
    {
        padding-left: 10px;
        padding-right: 10px;
    }
    .form-group mb-2{
        padding-left: 10px;
        padding-right: 10px;
    }
</style>
{% endblock %}

restaurant_project/templates/procesos/registro_usuario.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block TitlePage %}
    {{'Mantenimiento | Usuarios'}}
{% endblock %}
{% block body %}
    <div class="container">
        <!-- breadcrumbs -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="#">Mantenimiento</a>
            </li>
            <li class="breadcrumb-item">
                <a href="#">Usuarios</a>
            </li>
            <li class="breadcrumb-item active">
                Registro
            </li>
        </ol>
        {% if registered %}
        <div class="alert alert-success" role="alert">
            Gracias por registrar el usuario.
        </div>
        <a class="btn btn-primary" href="{% url 'procesos:registro_usuarios' %}">Volver</a>
        {% else %}
        <div class="alert alert-primary" role="alert">
            El propósito de este sitio es registrar usuarios.
        </div>
        <div class="alert alert-warning" role="alert">
            Si necesita cambiar datos de los usuarios ingrese <a href="{% url 'admin:index' %}">aquí.</a>
        </div>
        <form enctype="multipart/form-data" method="POST">{% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" value="Registrar" class="btn btn-success">
        </form>
        {% endif %}
    </div>
{% endblock %}

{% block JavaScriptFiles %}

{% endblock %}