restaurant_project/inventario/urls.py
from django.conf.urls import url
from inventario import views
from django.contrib.auth.decorators import login_required
app_name = 'inventario'

urlpatterns = [
    # urls del api rest para el crud de producto
    url(r'^productos/$', views.productos, name='productos'),
    url(r'^productos_list/$', login_required(views.Get_producto_List.as_view()), name='productos_list'),
    url(r'^productos_filter/$', login_required(views.Get_producto_ListFilter.as_view()), name='productos_filter'),
    url(r'^productos_create/$', login_required(views.Get_producto_Create.as_view()), name='productos_create'),
    url(r'^productos_update/$', login_required(views.Get_producto_Update.as_view()), name='productos_update'),
    url(r'^productos_delete/$', login_required(views.Get_producto_Delete.as_view()), name='productos_delete'),
    # urls de las vistas basadas en clases para los reportes de inventario
    url(r'^reportes/$', login_required(views.ReporteDeExistenciaList.as_view()), name='reportes'),
    url(r'^reportes/(?P<pk>\d+)/$', login_required(views.ReporteDeExistenciaDetail.as_view()), name='reporte_detail'),
    url(r'^reportes/(?P<pk>\d+)/pdf', login_required(views.pdf_view.as_view()), name='reporte_detail_pdf'),
    url(r'^reportes/create/$', login_required(views.ReporteDeExistenciaCreateView.as_view()), name='reporte_create'),
    url(r'^reportes/update/(?P<pk>\d+)/$', login_required(views.ReporteDeExistenciaUpdateView.as_view()), name='reporte_update'),
    url(r'^reportes/delete/(?P<pk>\d+)/$', login_required(views.ReporteDeExistenciaDeleteView.as_view()), name='reporte_delete'),
    # urls del api rest para el crud de existencias
    url(r'^existencias_list/$', login_required(views.GetExistenciasList.as_view()), name='existencias_list'),
    url(r'^existencias_create/$', login_required(views.GetExistenciasCreate.as_view()), name='existencias_create'),
    url(r'^existencias_delete/$', login_required(views.GetExistenciasDelete.as_view()), name='existencias_delete'),
    url(r'^existencias_update/$', login_required(views.GetExistenciasUpdate.as_view()), name='existencias_update'),
]

restaurant_project/procesos/urls.py
from django.conf.urls import url
from procesos import views
from django.contrib.auth.decorators import login_required

app_name = 'procesos'

urlpatterns = [
    url(r'^usuarios/', login_required(views.registro_usuario), name='registro_usuarios'),
    url(r'^sesion_caja/', login_required(views.sesion_caja), name='sesion_caja'),
    url(r'^create_sesion_caja/', login_required(views.CreateSesionCaja.as_view()), name='create_sesion_caja'),
    url(r'^cerrar_sesion_caja/', login_required(views.CerrarSesionCaja.as_view()), name='cerrar_sesion_caja'),
    url(r'^lista_sesion_caja/', login_required(views.SesionList.as_view()), name='lista_sesion_caja'),
    url(r'^detalle_sesion_caja/', login_required(views.DetalleSesionCaja.as_view()), name='detalle_sesion_caja'),
    # urls utiles para realizar ordenes
    url(r'^panel_mesas/', login_required(views.PanelMesasView.as_view()), name='panel_mesas'),
    url(r'^abrir_orden/', login_required(views.AbrirOrden.as_view()), name='abrir_orden'),
    url(r'^detalle_orden/(?P<pk>\d+)/$', login_required(views.detalle_orden.as_view()), name='detalle_orden'),
    url(r'^orden_detail/', login_required(views.OrdenDetail.as_view()), name='orden_detail'),
    url(r'^orden_condetalles_detail/', login_required(views.OrdenConDetallesDetailList.as_view()), name='orden_condetalle_detail'),
    url(r'^lista_ordenes/', login_required(views.GetOrdenesList.as_view()), name='orden_list'),
    url(r'^lista_ordenesporestado', login_required(views.GetOrdenesPorEstadoList.as_view()), name='orden_porestado_list'),
    url(r'^ordenes_activas', login_required(views.OrdenesActivas.as_view()), name='ordenes_activas'),
    url(r'^orden_update', login_required(views.GetOrdenesUpdate.as_view()), name='orden_update'),
    url(r'^orden_id', login_required(views.OrdenPago.as_view()), name="orden_id"),
    url(r'^lista_perfiles', login_required(views.PerfilDeUsuarioList.as_view()), name="lista_perfiles"),
    # urls utiles para realizar detalle de orden
    url(r'^create_detalle_orden', login_required(views.CreateDetalleOrden.as_view()), name='create_detalle_orden'),
    url(r'^update_detalle_orden', login_required(views.UpdateDetalleOrden.as_view()), name='update_detalle_orden'),
    url(r'^delete_detalle_orden', login_required(views.DeleteDetalleOrden.as_view()), name='delete_detalle_orden'),
    url(r'^detail_detalle_orden', login_required(views.DetalleOrdenDetail.as_view()), name='detail_detalle_orden'),
    # facturar
    url(r'^facturar', login_required(views.FacturarView.as_view()), name='facturar'),
    url(r'^detail_orden_mesa', login_required(views.OrdenDetailMesa.as_view()), name='detail_orden_mesa'),
    url(r'^pago/(?P<pk>\d+)/$', login_required(views.PagoView.as_view()), name="pago"),
    url(r'^pago/(?P<pk>\d+)/pdf/$', login_required(views.FacturaView.as_view()), name="factura_pdf"),
    url(r'^create_pago', login_required(views.GetCreatePago.as_view()), name="create_pago"),
    # historial de ordenes
    url(r'^historial', login_required(views.HistorialList.as_view()), name='historial'),
]

restaurant_project/restaurant_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from procesos import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^restaurant/', include('restaurant_application.urls')),
    url(r'^inventario/', include('inventario.urls')),
    url(r'^procesos/', include('procesos.urls')),
    url(r'^logout/', views.user_logout, name='logout'),
    url(r'^login', views.user_login, name='login'),
    url(r'^$', views.index, name='index'),
]

restaurant_project/inventario/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Producto(models.Model):
    KILOGRAMOS = 'kg'
    LIBRAS = 'lbl'
    TONELADAS_LARGAS = 'tnl'
    TONELADAS_METRICAS = 'tnm'
    TONELADAS_CORTAS = 'tnc'
    GRAMOS = 'g'
    UNIDADES = 'u'
    LITROS = 'lt'
    GALONES = 'gal'
    BARRILES = 'bar'
    LATAS = 'lts'
    CAJAS = 'caj'
    MILLARES = 'mil'
    METROS_CUBICOS = 'm3'
    METROS = 'm'
    OTROS = 'o'
    UNIDAD_DE_MEDIDA_CHOICES = (
        (KILOGRAMOS,'Kilogramos'),
        (LIBRAS, 'Libras'),
        (TONELADAS_LARGAS, 'Toneladas Largas'),
        (TONELADAS_METRICAS, 'Toneladas Metricas'),
        (TONELADAS_CORTAS, 'Toneladas Cortas'),
        (GRAMOS, 'Gramos'),
        (UNIDADES, 'Unidades'),
        (LITROS, 'Litros'),
        (GALONES, 'Galones'),
        (BARRILES, 'Barriles'),
        (LATAS, 'Latas'),
        (CAJAS, 'Cajas'),
        (MILLARES, 'Millares'),
        (METROS_CUBICOS, 'Metros cúbicos'),
        (METROS, 'Metros'),
        (OTROS, 'Otros'),
    )
    nombre = models.CharField(max_length=100)
    unidad_de_medida = models.CharField(
                        choices= UNIDAD_DE_MEDIDA_CHOICES,
                        default = UNIDADES,
                        max_length=30
                    )
    
    def __str__(self):
        return '{} - {}'.format(self.id , self.nombre)

class ReporteDeExistencia(models.Model):
    fecha_reporte = models.DateField()
    observaciones = models.TextField(max_length=512, blank=True)
    class Meta():
        ordering = ['fecha_reporte']

    def __str__(self):
        return 'Reporte de existencias a fecha {}'.format(self.fecha_reporte)
    def get_absolute_url(self):
        return reverse("inventario:reporte_detail", kwargs={'pk':self.pk})

class Existencia(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    reporte_de_existencia = models.ForeignKey(ReporteDeExistencia, on_delete=models.CASCADE, related_name='existencias', default=None)
    existencias = models.PositiveIntegerField()
    
    def __str__(self):
        unidad_de_medida_producto = ''
        for unidad_de_medida in Producto.UNIDAD_DE_MEDIDA_CHOICES:
            if(unidad_de_medida[0] == self.producto.unidad_de_medida):
                unidad_de_medida_producto = unidad_de_medida[1]
        return 'Códido: {} - Descripción: {} - Cantidad: {} - Unidad: {} - Fecha: {}'.format(self.producto.id, self.producto.nombre, self.existencias, unidad_de_medida_producto, self.reporte_de_existencia.fecha_reporte)

restaurant_project/inventario/forms.py
from django import forms
from inventario.models import Producto, Existencia

class ProductoForm(forms.ModelForm):

    class Meta():
        model = Producto
        fields = ('nombre', 'unidad_de_medida',)

class ExistenciaForm(forms.ModelForm):

    class Meta():
        model = Existencia
        fields = ('producto', 'existencias')

restaurant_project/inventario/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response
from inventario.models import Producto, ReporteDeExistencia, Existencia
from inventario.serializers import ProductoSerializer, ExistenciaSerializer, ReporteDeExistenciaSerializer
from django.http import JsonResponse, HttpResponse
from inventario.forms import ProductoForm, ExistenciaForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views import View
from io import BytesIO
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, Table, TableStyle, SimpleDocTemplate
from reportlab.lib.enums import TA_JUSTIFY, TA_LEFT, TA_CENTER
from reportlab.lib import colors

class Get_producto_Create(APIView):
    def get(self, request):
        producto = Producto.objects.create(nombre=request.GET['nombre'], unidad_de_medida=request.GET['unidad_de_medida'])
        producto.save()
        return JsonResponse({'respuesta':'ok'})

class Get_producto_Update(APIView):
    def get(self, request):
        producto = Producto.objects.filter(id=request.GET['id']).update(nombre=request.GET['nombre'], unidad_de_medida=request.GET['unidad_de_medida'])
        return JsonResponse({'respuesta':'ok'})


class Get_producto_Delete(APIView):
    def get(self, request):
        producto = Producto.objects.filter(id=request.GET['id']).delete()
        return JsonResponse({'respuesta':'ok'})

class Get_producto_List(APIView):
    def get(self, request):
        productos = Producto.objects.all().order_by("id")
        serialized = ProductoSerializer(productos, many=True)
        return Response(serialized.data)

class Get_producto_ListFilter(APIView):
    def get(self, request):
        productos = Producto.objects.filter(nombre__startswith=request.GET['nombre']).order_by('id')
        serialized = ProductoSerializer(productos, many=True)
        return Response(serialized.data)
@login_required
def productos(request):
    form = ProductoForm()
    context = {'form':form}
    return render(request, 'inventario/productos.html', context)

class ReporteDeExistenciaList(ListView):
    model = ReporteDeExistencia
    context_object_name = 'reportes'

class ReporteDeExistenciaDetail(DetailView):
    model = ReporteDeExistencia
    context_object_name = 'reporte'
    template_name = 'inventario/reportedeexistencia_detail.html'
    existenciaForm = ExistenciaForm()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.existenciaForm
        return context

class ReporteDeExistenciaCreateView(CreateView):
    model = ReporteDeExistencia
    fields = ['fecha_reporte','observaciones']

class ReporteDeExistenciaUpdateView(UpdateView):
    model = ReporteDeExistencia
    fields = ['fecha_reporte', 'observaciones']

class ReporteDeExistenciaDeleteView(DeleteView):
    model = ReporteDeExistencia
    success_url = reverse_lazy("inventario:reportes")

class GetExistenciasList(APIView):
    def get(self, request):
        existencias = Existencia.objects.filter(reporte_de_existencia=request.GET['id_reporte']).order_by('id')
        serialized = ExistenciaSerializer(existencias, many=True)
        return Response(serialized.data)

class GetExistenciasCreate(APIView):
    def get(self, request):
        id_producto = int(request.GET['id_producto'])
        producto = Producto.objects.filter(id=id_producto).get()
        id_reporte = int(request.GET['id_reporte'])
        reporte = ReporteDeExistencia.objects.filter(id=id_reporte).get()
        existencia = Existencia.objects.create(reporte_de_existencia=reporte, producto=producto ,existencias=request.GET['existencias'])
        existencia.save()

        existencias = Existencia.objects.filter(reporte_de_existencia=id_reporte).order_by('id')
        serialized = ExistenciaSerializer(existencias, many=True)
        return Response(serialized.data)

class GetExistenciasUpdate(APIView):
    def get(self, request):
        id_producto = int(request.GET['id_producto'])
        producto = Producto.objects.filter(id=id_producto).get()
        existencia = Existencia.objects.filter(id=request.GET['id']).update(producto=producto ,existencias=request.GET['existencias'])
        
        id_reporte = int(request.GET['id_reporte'])
        existencias = Existencia.objects.filter(reporte_de_existencia=id_reporte).order_by('id')
        serialized = ExistenciaSerializer(existencias, many=True)
        return Response(serialized.data)

class GetExistenciasDelete(APIView):
    def get(self, request):
        existencia = Existencia.objects.filter(id=request.GET['id']).delete()
        existencias = Existencia.objects.filter(reporte_de_existencia=request.GET['id_reporte']).order_by('id')
        serialized = ExistenciaSerializer(existencias, many=True)
        return Response(serialized.data)

class pdf_view(View):
    def get(self, request, pk):
        reporte = ReporteDeExistencia.objects.get(id=pk)

        reporte_serialized = ReporteDeExistenciaSerializer(reporte, many=False)

        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="{}.pdf"'.format(reporte.__str__())

        buffer = BytesIO()

        styles = getSampleStyleSheet()
        styleN = styles["BodyText"]
        styleN.alignment = TA_LEFT
        styleBH = styles["Normal"]
        styleBH.alignment = TA_CENTER

        doc = SimpleDocTemplate(buffer, pagesize=letter)
        
        elements = []


        #Encabezado
        encabezado = Paragraph('''<b>HOTEL Y RESTAURANTE PUNTA ROCA OLAS</b>''', styleBH)
        subtitulo = Paragraph('''Reporte de existencias a la fecha 16/07/2018.<br/><br/>''', styleBH)

        # Headers
        hcod = Paragraph('''<b>Cod.</b>''', styleN)
        hdesc = Paragraph('''<b>Descripción</b>''', styleN)
        hcant = Paragraph('''<b>Cantidad</b>''', styleN)
        huni = Paragraph('''<b>Unidad</b>''', styleN)
        obs = Paragraph('''<br/><b>Observaciones:</b><br/>{}'''.format(reporte_serialized.data['observaciones']),styleN)

        data= [[hcod, hdesc, hcant, huni]]

        for i in range(len(reporte_serialized.data['existencias'])):
            e = reporte_serialized.data['existencias'][i]
            unidad_de_medida_producto = ''
            for unidad_de_medida in Producto.UNIDAD_DE_MEDIDA_CHOICES:
                if(unidad_de_medida[0] == e['producto']['unidad_de_medida'] ):
                    unidad_de_medida_producto = unidad_de_medida[1]
            
            data.append([e['producto']['id'], e['producto']['nombre'], e['existencias'], unidad_de_medida_producto])

        t = Table(data)
        t.setStyle([('INNERGRID', (0,0), (-1,-1), 0.25, colors.black),
                    ('BOX', (0,0), (-1,-1), 0.25, colors.black)])

        elements.append(encabezado)
        elements.append(subtitulo)
        elements.append(t)
        elements.append(obs)
        doc.build(elements)
        response.write(buffer.getvalue())
        buffer.close()

        return response

restaurant_project/templates/inventario/productos.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block TitlePage %}
    {{'Productos'}} 
{% endblock %} 
{% block body%}
<div class="container">
    <!-- breadcrumbs -->
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="#">Inventario</a>
        </li>
        <li class="breadcrumb-item active">
            Productos
        </li>
    </ol>
    <div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-table"></i> Productos &nbsp;
        <button id="btn-registrar-producto" type="button" class="btn btn-success" data-toggle="modal" data-target="#productoModal">Nuevo</button>
    </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="tablaProductos" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Nombre</th>
                            <th>Unidad de medida</th>
                            <th width="300px">Acciones</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% include 'inventario/productos_modal.html' %} 
{% endblock %} 
{% block JavaScriptFiles %}
<script>
    var unidad_de_medida = {
            kg: "Kilogramos",
            lbl: "Libras",
            tnl: "Toneladas Largas",
            tnm: "Toneladas Métricas",
            tnc: "Toneladas Cortas",
            g: "Gramos",
            u: "Unidades",
            lt: "Litros",
            gal: "Galones",
            bar: "Barriles",
           lts: "Latas",
            caj: "Cajas",
            mil: "Millares",
            m3: "Metros cúbicos",
            m: "Metros",
            o: "Otros"
        };
    function cargarDatos() {
        var html = ``;
        $.ajax({
            url: "{% url 'inventario:productos_list' %}",
            type: 'GET',
            dataType: 'json',
            success: (data) => {
                for(let i = 0; i < data.length; i++){
                    html += `<tr>
                                <td>${data[i].id}</td>
                                <td>${data[i].nombre}</td>
                                <td class="${data[i].unidad_de_medida}">${unidad_de_medida[data[i].unidad_de_medida]}</td>
                                <td>
                                    <button type="button" class="btn btn-outline-success editar" value=${data[i].id}>Editar</button>
                                    <button type="button" class="btn btn-outline-danger eliminar" value=${data[i].id}>Eliminar</button>
                                </td>
                             </tr>`;
                }
                $('#tablaProductos tbody').html(html);
            }
        });
    }
    $(document).ready(() => {
        cargarDatos();
    });
    $('#guardar').on('click', function () {
        $.ajax({
            url: "{% url 'inventario:productos_create' %}",
            data: {
                nombre: $('#id_nombre').val(),
                unidad_de_medida: $('#id_unidad_de_medida').val()
            },
            type: 'GET',
            dataType: 'json',
            success: function (data) {
                $(".modal").modal("hide");
                cargarDatos();
            }
        });
    });
    $(document).on('click', '.editar', function(){
        $("#productoModalEditar").modal("show");
        $("#productoModalLabelEditar").html(`Editar producto con Id: ${$(this).val()}`);
        $("#productoModalEditar #id_nombre").val($(this).parents("tr").find("td")[1].innerText);
        $("#productoModalEditar #id_unidad_de_medida").val($(this).parents("tr").find("td")[2].classList[0]);
        $("#actualizar").val($(this).val());
    });
    $('#actualizar').on('click', function () {
        $.ajax({
            url: "{% url 'inventario:productos_update' %}",
            data: {
                id: $(this).val(),
                nombre: $('#productoModalEditar #id_nombre').val(),
                unidad_de_medida: $('#productoModalEditar #id_unidad_de_medida').val()
            },
            type: 'GET',
            dataType: 'json',
            success: function (data) {
                $(".modal").modal("hide");
                cargarDatos();
            }
        });
    });
    $(document).on('click', '.eliminar', function(){
        $("#productoModalEliminar").modal("show");
        $("#productoModalLabelEliminar").html(`Eliminar producto con Id: ${$(this).val()}`);
        $("#productoModalEliminar .modal-body").html(`<h5>¿Está seguro de eliminar este producto?<br>Esta operación no puede ser revertida</h5>`);
        $("#eliminar").val($(this).val());
    });
    $('#eliminar').on('click', function () {
        $.ajax({
            url: "{% url 'inventario:productos_delete' %}",
            data: {
                id: $(this).val()
            },
            type: 'GET',
            dataType: 'json',
            success: function (data) {
                $(".modal").modal("hide");
                cargarDatos();
            }
        });
    });
</script>
{% endblock %}

restaurant_project/templates/inventario/reportedeexistencia_detail.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block TitlePage %}
    {{'Inventario | Detalle del reporte'}}
{% endblock %}
{% block body %}
<link rel="stylesheet" href="{% static 'css/select2.min.css' %}">
    <div class="container">
        <!-- breadcrumbs -->
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="#">Inventario</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'inventario:reportes' %}">Reportes</a>
            </li>
            <li class="breadcrumb-item active">
                {{ reporte.id }}
            </li>
        </ol>
        <div class="card">
            <h5 class="card-header">{{ reporte }}
                <a href="{% url 'inventario:reporte_delete' pk=reporte.pk %}">
                    <button class="btn btn-danger" id="borrar-reporte">Borrar</button>
                </a>
                <a href="{% url 'inventario:reporte_update' pk=reporte.pk %}">
                    <button class="btn btn-warning" id="editar-reporte">Editar</button>
                </a>
                <a href="pdf">
                    <button class="btn btn-success" id="reporte-pdf">
                        Generar
                        <i class="fa fa-file-pdf-o" aria-hidden="true"></i>
                    </button>
                </a>
            </h5>
            <div class="card-body">
                <h5>
                    Producto:&nbsp;&nbsp;
                    {{ form.producto }}
                    Existencias: {{ form.existencias }}
                    <button class="btn btn-primary" id="btn-agregar">
                        <i class="fa fa-plus-square" aria-hidden="true"></i>
                        Agregar
                    </button>
                </h5>
                <table class="table table-bordered table-striped" id="tablaExistencias">
                    <thead class="thead-dark">
                        <th>Código</th>
                        <th>Descripción</th>
                        <th>Cantidad</th>
                        <th>Unidad</th>
                        <th>Acciones</th>
                    </thead>
                    <tbody>
                        
                    </tbody>
                </table>
                <h5 class="card-title">Observaciones:</h5>
                {{ reporte.observaciones }}
            </div>
        </div>
        {% include 'inventario/reportedeexistencia_detail_modal.html' %}
    </div>
<style>
    #reporte-pdf
    {
        float: right;
        margin-right: 2px;
    }
    #editar-reporte
    {
        float: right;
        margin-right: 2px;
    }
    #borrar-reporte
    {
        float: right;
    }
    select
    {
        min-width: 250px;
    }
</style>
{% endblock %}

{% block JavaScriptFiles %}
<script src="{% static 'js/select2.min.js' %}"></script>
<script>
    var unidad_de_medida = {
            kg: "Kilogramos",
            lbl: "Libras",
            tnl: "Toneladas Largas",
            tnm: "Toneladas Métricas",
            tnc: "Toneladas Cortas",
            g: "Gramos",
            u: "Unidades",
            lt: "Litros",
            gal: "Galones",
            bar: "Barriles",
           lts: "Latas",
            caj: "Cajas",
            mil: "Millares",
            m3: "Metros cúbicos",
            m: "Metros",
            o: "Otros"
        };
    $(document).ready(function() {
        $('#id_producto').select2();
        $("#existenciaModalEditar #id_producto").attr('id', 'id_producto_2')
        
        $.ajax({
            url: "{% url 'inventario:existencias_list' %}",
            data: {
                id_reporte: "{{reporte.id}}"
            },
            type: 'GET',
            dataType: 'json',
            success: (data) => {
                cargarDatos(data);
            }
        });
    });
    function cargarDatos(data) {
        var html = ``;
        
        for(let i = 0; i < data.length; i++){
            html += `<tr>
                        <td>${data[i].producto.id}</td>
                        <td>${data[i].producto.nombre}</td>
                        <td>${data[i].existencias}</td>
                        <td class="${data[i].unidad_de_medida}">${unidad_de_medida[data[i].producto.unidad_de_medida]}</td>
                        <td>
                            <button type="button" class="btn btn-outline-success editar" value=${data[i].id}>Editar</button>
                            <button type="button" class="btn btn-outline-danger eliminar" value=${data[i].id}>Eliminar</button>
                        </td>
                     </tr>`;
            }
            $('#tablaExistencias tbody').html(html);
    }
    $("#btn-agregar").on('click', () => {
        $.ajax({
            url: "{% url 'inventario:existencias_create' %}",
            data: {
                id_reporte: "{{ reporte.id }}",
                id_producto: $("#id_producto").val(),
                existencias: $("#id_existencias").val()
            },
            type: 'GET',
            dataType: 'json',
            success: (data) => {
                cargarDatos(data);
                limpiar();
            },
            error: function (xhr, ajaxOptions, thrownError) {
                
                if(xhr.status === 500){
                    alert('ERROR: Debe seleccionar un producto e introducir una cantidad.');
                }
                else{
                    alert(`Error ${xhr.status}: ${thrownError}`);
                }
            }
        });
    });
    function limpiar()
    {
        $('input').val('');
        $('select').val(null);
        $('#select2-id_producto-container').text('---------')
    }
    $(document).on('click', '.eliminar', function(){
        $("#existenciaModalEliminar").modal("show");
        $("#existenciaModalLabelEliminar").html(`Eliminar el registro?`);
        $("#eliminar").val($(this).val());
    });
    $('#eliminar').on('click', function () {
        $.ajax({
            url: "{% url 'inventario:existencias_delete' %}",
            data: {
                id: $(this).val(),
                id_reporte: "{{ reporte.id }}"
            },
            type: 'GET',
            dataType: 'json',
            success: function (data) {
                $(".modal").modal("hide");
                cargarDatos(data);
            }
        });
    });
    $(document).on('click', '.editar', function(){
        $("#existenciaModalEditar").modal("show");
        $("#id_producto_2").val($(this).parents("tr").find("td")[0].innerHTML);
        $('#id_producto_2').select2({
            dropdownParent: $('#existenciaModalEditar')
        });
        $("#existenciaModalEditar #id_existencias").val($(this).parents("tr").find("td")[2].innerHTML);
        $("#actualizar").val($(this).val());
    });
    $('#actualizar').on('click', function () {
        $.ajax({
            url: "{% url 'inventario:existencias_update' %}",
            data: {
                id: $(this).val(),
                id_producto: $("#id_producto_2").val(),
                existencias: $("#existenciaModalEditar #id_existencias").val(),
                id_reporte: "{{ reporte.id }}"
            },
            type: 'GET',
            dataType: 'json',
            success: function (data) {
                $(".modal").modal("hide");
                cargarDatos(data);
            }
        });
    });
</script>
{% endblock %}