restaurant_project/inventario/urls.py
from django.conf.urls import url
from inventario import views
from django.contrib.auth.decorators import login_required
app_name = 'inventario'

urlpatterns = [
    # urls del api rest para el crud de producto
    url(r'^productos/$', views.productos, name='productos'),
    url(r'^productos_list/$', login_required(views.Get_producto_List.as_view()), name='productos_list'),
    url(r'^productos_filter/$', login_required(views.Get_producto_ListFilter.as_view()), name='productos_filter'),
    url(r'^productos_create/$', login_required(views.Get_producto_Create.as_view()), name='productos_create'),
    url(r'^productos_update/$', login_required(views.Get_producto_Update.as_view()), name='productos_update'),
    url(r'^productos_delete/$', login_required(views.Get_producto_Delete.as_view()), name='productos_delete'),
    # urls de las vistas basadas en clases para los reportes de inventario
    url(r'^reportes/$', login_required(views.ReporteDeExistenciaList.as_view()), name='reportes'),
    url(r'^reportes/(?P<pk>\d+)/$', login_required(views.ReporteDeExistenciaDetail.as_view()), name='reporte_detail'),
    url(r'^reportes/(?P<pk>\d+)/pdf', login_required(views.pdf_view.as_view()), name='reporte_detail_pdf'),
    url(r'^reportes/create/$', login_required(views.ReporteDeExistenciaCreateView.as_view()), name='reporte_create'),
    url(r'^reportes/update/(?P<pk>\d+)/$', login_required(views.ReporteDeExistenciaUpdateView.as_view()), name='reporte_update'),
    url(r'^reportes/delete/(?P<pk>\d+)/$', login_required(views.ReporteDeExistenciaDeleteView.as_view()), name='reporte_delete'),
    # urls del api rest para el crud de existencias
    url(r'^existencias_list/$', login_required(views.GetExistenciasList.as_view()), name='existencias_list'),
    url(r'^existencias_create/$', login_required(views.GetExistenciasCreate.as_view()), name='existencias_create'),
    url(r'^existencias_delete/$', login_required(views.GetExistenciasDelete.as_view()), name='existencias_delete'),
    url(r'^existencias_update/$', login_required(views.GetExistenciasUpdate.as_view()), name='existencias_update'),
]

restaurant_project/procesos/urls.py
from django.conf.urls import url
from procesos import views
from django.contrib.auth.decorators import login_required

app_name = 'procesos'

urlpatterns = [
    url(r'^usuarios/', login_required(views.registro_usuario), name='registro_usuarios'),
    url(r'^sesion_caja/', login_required(views.sesion_caja), name='sesion_caja'),
    url(r'^create_sesion_caja/', login_required(views.CreateSesionCaja.as_view()), name='create_sesion_caja'),
    url(r'^cerrar_sesion_caja/', login_required(views.CerrarSesionCaja.as_view()), name='cerrar_sesion_caja'),
    url(r'^lista_sesion_caja/', login_required(views.SesionList.as_view()), name='lista_sesion_caja'),
    url(r'^detalle_sesion_caja/', login_required(views.DetalleSesionCaja.as_view()), name='detalle_sesion_caja'),
    # urls utiles para realizar ordenes
    url(r'^panel_mesas/', login_required(views.PanelMesasView.as_view()), name='panel_mesas'),
    url(r'^abrir_orden/', login_required(views.AbrirOrden.as_view()), name='abrir_orden'),
    url(r'^detalle_orden/(?P<pk>\d+)/$', login_required(views.detalle_orden.as_view()), name='detalle_orden'),
    url(r'^orden_detail/', login_required(views.OrdenDetail.as_view()), name='orden_detail'),
    url(r'^orden_condetalles_detail/', login_required(views.OrdenConDetallesDetailList.as_view()), name='orden_condetalle_detail'),
    url(r'^lista_ordenes/', login_required(views.GetOrdenesList.as_view()), name='orden_list'),
    url(r'^lista_ordenesporestado', login_required(views.GetOrdenesPorEstadoList.as_view()), name='orden_porestado_list'),
    url(r'^ordenes_activas', login_required(views.OrdenesActivas.as_view()), name='ordenes_activas'),
    url(r'^orden_update', login_required(views.GetOrdenesUpdate.as_view()), name='orden_update'),
    url(r'^orden_id', login_required(views.OrdenPago.as_view()), name="orden_id"),
    url(r'^lista_perfiles', login_required(views.PerfilDeUsuarioList.as_view()), name="lista_perfiles"),
    # urls utiles para realizar detalle de orden
    url(r'^create_detalle_orden', login_required(views.CreateDetalleOrden.as_view()), name='create_detalle_orden'),
    url(r'^update_detalle_orden', login_required(views.UpdateDetalleOrden.as_view()), name='update_detalle_orden'),
    url(r'^delete_detalle_orden', login_required(views.DeleteDetalleOrden.as_view()), name='delete_detalle_orden'),
    url(r'^detail_detalle_orden', login_required(views.DetalleOrdenDetail.as_view()), name='detail_detalle_orden'),
    # facturar
    url(r'^facturar', login_required(views.FacturarView.as_view()), name='facturar'),
    url(r'^detail_orden_mesa', login_required(views.OrdenDetailMesa.as_view()), name='detail_orden_mesa'),
    url(r'^pago/(?P<pk>\d+)/$', login_required(views.PagoView.as_view()), name="pago"),
    url(r'^pago/(?P<pk>\d+)/pdf/$', login_required(views.FacturaView.as_view()), name="factura_pdf"),
    url(r'^create_pago', login_required(views.GetCreatePago.as_view()), name="create_pago"),
    # historial de ordenes
    url(r'^historial', login_required(views.HistorialList.as_view()), name='historial'),
]

restaurant_project/restaurant_application/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required


app_name = "restaurant"

urlpatterns = [

        #URL PARA CATEGORI PLATILLO

    url(r'^categoria_platillos/$', views.index_categoria_platillos, name='index_categoria_platillos'),
    url(r'^create_categoria_platillos/$', login_required(views.CategoriaPlatilloCreate.as_view()), name='create_categoria_platillos'),
    url(r'^lista_categoria_platillos/$', login_required(views.CategoriaPlatilloList.as_view()), name='lista_categoria_platillos'),
    url(r'^lista_categoria_platillos_con_platillos/$', login_required(views.CategoriaPlatilloConPlatillosList.as_view()), name='lista_categoria_platillos_con_platillos'),
    url(r'^editar_categoria_platillos/$', login_required(views.CategoriaPlatilloUpdate.as_view()), name='editar_categoria_platillos'),
    url(r'^eliminar_categoria_platillos/$', login_required(views.CategoriaPlatilloDelete.as_view()), name='eliminar_categoria_platillos'),


        #URL PARA PLATILLOS

    url(r'^platillos/$', views.index_platillos, name='index_platillos'),
    url(r'^create_platillos/$', login_required(views.PlatilloCreate.as_view()), name='create_platillos'),
    url(r'^lista_platillos/$', login_required(views.PlatilloList.as_view()), name='lista_platillos'),
    url(r'^platillo_detail/$', login_required(views.PlatilloDetail.as_view()), name='platillo_detail'),
    url(r'^editar_platillos/$', login_required(views.PlatilloUpdate.as_view()), name='editar_platillos'),
    url(r'^eliminar_platillos/$', login_required(views.PlatilloDelete.as_view()), name='eliminar_platillos'),

        #URL PARA MESAS

    url(r'^mesas/$', views.index_mesas, name='index_mesas'),
    url(r'^create_mesas/$', login_required(views.MesaCreate.as_view()), name='create_mesas'),
    url(r'^lista_mesas/$', login_required(views.MesaList.as_view()), name='lista_mesas'),
    url(r'^editar_mesas/$', login_required(views.MesaUpdate.as_view()), name='editar_mesas'),
    url(r'^eliminar_mesas/$', login_required(views.MesaDelete.as_view()), name='eliminar_mesas'),

        #URL PARA EMPLEADOS

    url(r'^empleados/$', views.index_empleados, name='index_empleados'),
    url(r'^create_empleado/$', login_required(views.EmpleadoCreate.as_view()), name='create_empleado'),
    url(r'^lista_empleados/$', login_required(views.EmpleadosList.as_view()), name='lista_empleados'),
    url(r'^detalle_empleado/$', login_required(views.EmpleadoDetalle.as_view()), name='detalle_empleado'),
    url(r'^editar_empleado/$', login_required(views.EmpleadoUpdate.as_view()), name='editar_empleado'),
    url(r'^eliminar_empleado/$', login_required(views.EmpleadoDelete.as_view()), name='eliminar_empleado'),
]

restaurant_project/restaurant_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from procesos import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^restaurant/', include('restaurant_application.urls')),
    url(r'^inventario/', include('inventario.urls')),
    url(r'^procesos/', include('procesos.urls')),
    url(r'^logout/', views.user_logout, name='logout'),
    url(r'^login', views.user_login, name='login'),
    url(r'^$', views.index, name='index'),
]

restaurant_project/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>
      {% block TitlePage %}
      {% endblock %}
    </title>
    <!-- Bootstrap core CSS-->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <!-- Page level plugin CSS-->
    <link href="{% static 'vendor/datatables/dataTables.bootstrap4.css' %}" rel="stylesheet">
    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet">
    <!-- JQuery UI -->
    <link href="{% static 'jquery-ui/jquery-ui.min.css' %}" rel="stylesheet">
    {% block cssFiles %}
    {% endblock %}
  </head>

  <body class="fixed-nav sticky-footer bg-dark" id="page-top">
    {% include 'base/navigation.html' %}
    <div class="content-wrapper">
      <div class="container-fluid">

      {% block body %}
      {% endblock %}
      <!-- /.container-fluid-->
      <!-- /.content-wrapper-->
      <footer class="sticky-footer">
        <div class="container">
          <div class="text-center">
            <small>Copyright © 2018</small>
          </div>
        </div>
      </footer>
      <!-- Scroll to Top Button-->
      <a class="scroll-to-top rounded" href="#page-top">
        <i class="fa fa-angle-up"></i>
      </a>
      <!-- Logout Modal-->
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
              <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
              </button>
            </div>
            <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
            <div class="modal-footer">
              <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
              <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
            </div>
          </div>
        </div>
      </div>
      <!-- Sesion modal -->
      <div class="modal" id="sesion-modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Debe habilitar una sesión.</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <div class="alert alert-danger" role="alert">
                Usted no tiene asignada una sesión de caja.
              </div>
            </div>
            <div class="modal-footer">
              <a href="{% url 'procesos:sesion_caja' %}"><button type="button" class="btn btn-primary" data-dismiss="modal">Aceptar</button>
            </div>
          </div>
        </div>
      </div>
      <!-- Bootstrap core JavaScript-->
      <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
      <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
      <!-- Core plugin JavaScript-->
      <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
      <!-- Page level plugin JavaScript-->
      <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>
      <script src="{% static 'vendor/datatables/jquery.dataTables.js' %}"></script>
      <script src="{% static 'vendor/datatables/dataTables.bootstrap4.js' %}"></script>
      <!-- Custom scripts for all pages-->
      <script src="{% static 'js/sb-admin.min.js' %}"></script>
      <!-- JQuery UI -->
      <script src="{% static 'jquery-ui/jquery-ui.min.js' %}"></script>
      <!-- Valida que existe una sesion para poder realizar una orden -->
      <script>
        function empleado(usuario_id, perfiles)
        {
            let empleado_id = null;
            for(let i = 0; i < perfiles.length; i++)
            {
                if(perfiles[i].usuario == usuario_id)
                {
                    empleado_id = perfiles[i].empleado;
                }
            }
            return empleado_id;
        }
        function comprobarSesion(){
          $.ajax({
            url: "{% url 'procesos:lista_sesion_caja' %}",
            type: 'get',
            dataType: 'json',
            success: (dataSesion) => {
              $.ajax({
                url: "{% url 'procesos:lista_perfiles' %}",
                type: 'get',
                dataType: 'json',
                success: function(dataPerfiles)
                {
                  let sesionActiva = false;
                  for(let i = 0; i < dataSesion.length; i++)
                  {
                    if(dataSesion[i].estado.toLowerCase() === "abierta" && empleado(parseInt("{{ user.id }}"), dataPerfiles) == dataSesion[i].cajero.idEmpleado)
                    {
                      sesionActiva = true;
                    }
                  }
                  if(!sesionActiva)
                  {
                    $("#sesion-modal").modal("show");
                  }
                  else{
                    window.location.href = "{% url 'procesos:panel_mesas' %}";
                  }
                }
              });

            }
          });
        }

      </script>
      {% block JavaScriptFiles %}
      {% endblock %}
    </div>
  </body>

</html>

restaurant_project/templates/base/modal.html
<!-- Modal -->
<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="labelModal"></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="cargarForm">

      </div>
    </div>
  </div>
</div>

restaurant_project/templates/base/navigation.html
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
  <a class="navbar-brand" href="#">Punta Roca</a>
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Ordenes">
        <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseOrdenes" data-parent="#exampleAccordion">
            <i class="fa fa-cutlery" aria-hidden="true"></i>
          <span class="nav-link-text">Ordenes</span>
        </a>
        <ul class="sidenav-second-level collapse" id="collapseOrdenes">
          {% if user.is_staff %}
          <li>
            <a href="{% url 'procesos:sesion_caja' %}">Sesiones</a>
          </li>
          {% endif %}
          <li>
            <a onclick="return comprobarSesion();" style="cursor: pointer;">Ordenar</a>
          </li>
          <li>
            <a href="{% url 'procesos:ordenes_activas' %}">Ordenes activas</a>
          </li>
          <li>
            <a href="{% url 'procesos:facturar' %}">Facturar</a>
          </li>
          {% if user.is_staff %}
            <li>
              <a href="{% url 'procesos:historial' %}">Historial</a>
            </li>
          {% endif %}
        </ul>
      </li>
      {% if user.is_staff %}
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Mantenimiento">
        <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMantenimiento" data-parent="#exampleAccordion">
          <i class="fa fa-wrench"></i>
          <span class="nav-link-text">Mantenimiento</span>
        </a>
        <ul class="sidenav-second-level collapse" id="collapseMantenimiento">
          <li>
            <a href="{% url 'restaurant:index_categoria_platillos' %}">Categoría de platillos</a>
          </li>
          <li>
            <a href="{% url 'restaurant:index_platillos' %}">Platillos</a>
          </li>
          <li>
            <a href="{% url 'restaurant:index_mesas' %}">Mesas</a>
          </li>
          <li>
            <a href="{% url 'restaurant:index_empleados' %}">Empleados</a>
          </li>
          <li>
            <a href="{% url 'procesos:registro_usuarios' %}">Usuarios</a>
          </li>
        </ul>
      </li>
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Inventario">
        <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseInventario" data-parent="#exampleAccordion">
            <i class="fa fa-book" aria-hidden="true"></i>

          <span class="nav-link-text">Inventario</span>
        </a>
        <ul class="sidenav-second-level collapse" id="collapseInventario">
          <li>
            <a href="{% url 'inventario:productos' %}">Productos</a>
          </li>
          <li>
            <a href="{% url 'inventario:reportes' %}">Reporte de existencias</a>
          </li>
        </ul>
      </li>
      {% endif %}
    </ul>

    <ul class="navbar-nav sidenav-toggler">
      <li class="nav-item">
        <a class="nav-link text-center" id="sidenavToggler">
          <i class="fa fa-fw fa-angle-left"></i>
        </a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item">
          <h3 style="color: white;">Usuario: {{ user.username }}</h3>
        </li>
        <li class="nav-item">

          <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
            <i class="fa fa-fw fa-sign-out"></i>Logout</a>

        </li>
        {% endif %}
      </ul>
  </div>
</nav>